### ISSUE TITLE
Is there a purpose for "chatbot/db"?

### ISSUE THREAD

**Issue by dataCobra** [bastienboutonnet/datafrittata-twitch-chatbot#16]
Hey @bastienboutonnet,

there are currently two db/ folders in the Repository.
 1. `/db/`
 2. `/chatbot/db/`

Since the second db folder has no purpose. Is this a mistake?

**Comment by bastienboutonnet** [comment]
I think it's a mistake or rather a side-effect of having ran the bot from the wrong place. So yeah I think we can knock off the second folder!
