### ISSUE TITLE
Create documentation for "bot_env_vars.env.sample"

### ISSUE THREAD

**Issue by dataCobra** [bastienboutonnet/datafrittata-twitch-chatbot#23]
Hey @bastienboutonnet,

since your latest commits I don't know what to add to my `bot_env_vars.env` file to make sure it works.

Could you add a documentation or include some links in this issue so I can go back to testing and coding? :slightly_smiling_face: 

Regards,
Ben

**Comment by bastienboutonnet** [comment]
Great question, I do need to write more extensive documention in the readme, but I'll do that off stream for now the comments I added in the sample file e958005 should send you in the right direction.
