### ISSUE TITLE
Please add elaborate README.md and Code Of Conduct.md. 

### ISSUE THREAD

**Issue by yasir-khilji-64** [bastienboutonnet/datafrittata-twitch-chatbot#7]
- Adding README.md will help others understand what the Repo is all about. 
- Adding Code of Conduct will help contributors, how to style the code and lint and other stuff.

**Comment by niyrme** [comment]
code styling is somewhat done with pre-commit and the .editorconfig file.
But adding some more to the README would be nice. yea

**Comment by bastienboutonnet** [comment]
I totally agree and will definitely do this off stream one day as I dont think it's great and exciting content to stream live.
